### ISSUE TITLE
styleSheet.getName is not a function

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#179]
getting this when using transpiled versions in demos.

```
TypeError: styleSheet.getName is not a function
    at ComponentStyle.generateAndInjectStyles (/Users/greada/Documents/workspace/sinner/dekk/@dekk/slide/node_modules/styled-components/dist/styled-components.cjs.js:1815:37)
    at StyledComponent.generateAndInjectStyles (/Users/greada/Documents/workspace/sinner/dekk/@dekk/slide/node_modules/styled-components/dist/styled-components.cjs.js:1492:40)
    at StyledComponent.componentWillMount (/Users/greada/Documents/workspace/sinner/dekk/@dekk/slide/node_modules/styled-components/dist/styled-components.cjs.js:1530:40)
    at resolve (/Users/greada/Documents/workspace/sinner/dekk/node_modules/react-dom/cjs/react-dom-server.node.development.js:2119:12)
    at ReactDOMServerRenderer.render (/Users/greada/Documents/workspace/sinner/dekk/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (/Users/greada/Documents/workspace/sinner/dekk/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at Object.renderToString (/Users/greada/Documents/workspace/sinner/dekk/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
    at render (<anonymous>:81:31)
    at /Users/greada/Documents/workspace/sinner/dekk/node_modules/@patternplate/cli/lib/start.js:162967:27
    at /Users/greada/Documents/workspace/sinner/dekk/node_modules/@patternplate/webpack-entry/lib/loader.js:276:27
```

```jsx
import React from 'react'
import Deck, {Elements} from '../'
import Slide from '@dekk/slide'

const Header = () => <header>Dekk Elements</header>

export default function() {
  return (
    <div>
      <Deck>
        <Elements>
          <Header />
        </Elements>
        <Slide>Slide 1</Slide>
      </Deck>
    </div>
  )
}
```

if I use the original src files I get problems with missing babel-loaders

```
"@patternplate/cli": "^2.0.0-57"
```

**Comment by pixelass** [comment]
seems to work like this:

```jsx
import React from 'react'
import Deck from '../deck'
import Slide from '../../../slide'
import Plugins from './'

const MyPlugin = props => {
  console.log(props)
  return null
}

export default function() {
  return (
    <Deck>
      <Plugins>
        <MyPlugin />
      </Plugins>
      <Slide>1</Slide>
    </Deck>
  )
}

```

**Comment by marionebl** [comment]
Looks like different `styled-components` versions in `dekk` and `@patternplate/render-styled-components`. Can you verify?

**Comment by marionebl** [comment]
I'll phase out official supported `@patternplate/render-styled-components` - this issue is most likely connected to it. You'll have to provide a custom renderer for SSR support with styled-components in the near future.
