### ISSUE TITLE
create fails when yarn is not installed

### ISSUE THREAD

**Issue by zmnv** [patternplate/patternplate#200]
I don't want to use yarn at all. Only npm.

Without yarn patternplate can't create new project:

```
$ patternplate create --out my-guides 

TypeError: Cannot read property 'patternplate' of null
    at main.catch.err (/usr/local/lib/node_modules/@patternplate/cli/lib/cli.js:389:11)
    at <anonymous>
/usr/local/lib/node_modules/@patternplate/cli/lib/cli.js:400
  throw reason;
  ^
```

Just setup **yarn** and **yarn add...** and it works.

**Comment by zmnv** [comment]
Just joke. It Doesn't.

zmnv:au-guides zmnv$ yarn start
yarn run v1.5.1

```
$ patternplate start
✔ Started on http://localhost:1337
(node:1990) UnhandledPromiseRejectionWarning: Error: Could not resolve "@patternplate/render-styled-components/mount" from /Users/zmnv/patternplate, /Users/zmnv/patternplate/au-guides
    at cascadeResolve (/Users/zmnv/patternplate/au-guides/node_modules/@patternplate/compiler/lib/compiler.js:406:11)
    at /Users/zmnv/patternplate/au-guides/node_modules/@patternplate/compiler/lib/compiler.js:342:25
    at /Users/zmnv/patternplate/au-guides/node_modules/@patternplate/webpack-entry/lib/webpack-entry.js:276:27
    at <anonymous>
(node:1991) UnhandledPromiseRejectionWarning: Error: Could not resolve "@patternplate/render-styled-components/render" from /Users/zmnv/patternplate, /Users/zmnv/patternplate/au-guides
    at cascadeResolve (/Users/zmnv/patternplate/au-guides/node_modules/@patternplate/compiler/lib/compiler.js:406:11)
    at /Users/zmnv/patternplate/au-guides/node_modules/@patternplate/compiler/lib/compiler.js:336:26
    at /Users/zmnv/patternplate/au-guides/node_modules/@patternplate/webpack-entry/lib/webpack-entry.js:276:27
    at <anonymous>
(node:1990) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1990) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1991) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by marionebl** [comment]
Thanks for reporting, I'l investigate right away. Could you provide the output of `patternplate -v`?

**Comment by marionebl** [comment]
Fix for second problem released via `v2.0.12`, at least for installs using `render-default`. Can you provide your `patternplate.config.js` and verify you have `@patternplate/render-styled-components` installed?

**Comment by marionebl** [comment]
Can reproduce the same error messages when starting a `styled-components`-referencing example with `@patternplate/render-styled-components` not being installed.

**Comment by marionebl** [comment]
The issue goes away when installing `@patternplate/render-styled-components`, see the example `package.json`: 

https://github.com/patternplate/patternplate/blob/28c0cb5f77e0896a3c2393e54cc04175ed0931ab/examples/styled-components/package.json#L26-L28
