### ISSUE TITLE
Error when starting patternplate (TypeError: Expected `moduleId`)

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#208]
### Description

I get an error in the console (terminal) when starting patternplate.

The error does not seem to have any impact.

The project was created using `npx create-patternplate --out my-patternplate --guide`

### Config 

```js
module.exports = {
  docs: [
    "manual/**/*.md"
  ],
  entry: [
    "lib/**/demo.js"
  ]
};

```

### Logs

<details>
  <summary>Error Log</summary>

```sh
11:23 $ yarn start
yarn run v1.5.1
$ patternplate start
✔ Started on http://localhost:1337
(node:33205) UnhandledPromiseRejectionWarning: TypeError: Expected `moduleId` to be of type `string`, got `undefined`
    at resolveFrom (/Users/greada/Workspace/Sinnerschrader/frontend-dev/frontend-dev-guide/node_modules/resolve-from/index.js:12:9)
    at module.exports.silent (/Users/greada/Workspace/Sinnerschrader/frontend-dev/frontend-dev-guide/node_modules/resolve-from/index.js:47:48)
    at bases.reduce (/Users/greada/Workspace/Sinnerschrader/frontend-dev/frontend-dev-guide/node_modules/@patternplate/compiler/lib/compiler.js:402:47)
    at Array.reduce (<anonymous>)
    at cascadeResolve (/Users/greada/Workspace/Sinnerschrader/frontend-dev/frontend-dev-guide/node_modules/@patternplate/compiler/lib/compiler.js:397:24)
    at /Users/greada/Workspace/Sinnerschrader/frontend-dev/frontend-dev-guide/node_modules/@patternplate/compiler/lib/compiler.js:336:26
    at /Users/greada/Workspace/Sinnerschrader/frontend-dev/frontend-dev-guide/node_modules/@patternplate/webpack-entry/lib/webpack-entry.js:276:27
    at <anonymous>
(node:33204) UnhandledPromiseRejectionWarning: TypeError: Expected `moduleId` to be of type `string`, got `undefined`
    at resolveFrom (/Users/greada/Workspace/Sinnerschrader/frontend-dev/frontend-dev-guide/node_modules/resolve-from/index.js:12:9)
    at module.exports.silent (/Users/greada/Workspace/Sinnerschrader/frontend-dev/frontend-dev-guide/node_modules/resolve-from/index.js:47:48)
    at bases.reduce (/Users/greada/Workspace/Sinnerschrader/frontend-dev/frontend-dev-guide/node_modules/@patternplate/compiler/lib/compiler.js:402:47)
    at Array.reduce (<anonymous>)
    at cascadeResolve (/Users/greada/Workspace/Sinnerschrader/frontend-dev/frontend-dev-guide/node_modules/@patternplate/compiler/lib/compiler.js:397:24)
    at /Users/greada/Workspace/Sinnerschrader/frontend-dev/frontend-dev-guide/node_modules/@patternplate/compiler/lib/compiler.js:342:25
    at /Users/greada/Workspace/Sinnerschrader/frontend-dev/frontend-dev-guide/node_modules/@patternplate/webpack-entry/lib/webpack-entry.js:276:27
    at <anonymous>
(node:33205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33205) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:33204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

</details>

### Environment

| name         | version |
|-------------:|---------|
| node         | v8.11.1 |
| npm          | 5.6.0   |
| patternplate | 2.1.5   |

**Comment by pixelass** [comment]
https://github.com/pixelass/patternplate-bugs

**Comment by pixelass** [comment]
The issue is related to the config (missing "render" and "mount" keys).

After adding those keys the error disappears.

**Comment by marionebl** [comment]
I'll add a `try-catch` level that creates better error messages for this, telling you explicitly: 

* there has to be a full set of config when providing `patternplate.config.js`
* `render` and `mount` are mandatory

**Comment by marionebl** [comment]
Also see #201

**Comment by marionebl** [comment]
Better error messages shipping as of `2.2.0`
