### ISSUE TITLE
better error handling

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#226]
I keep running into the same issues: 

I've been trying to figure out the issues for several hours but don't see what's wrong.
The error message does not help in any way.

This is less about the issue than the fact that errors could deliver better information.

## terminal
```
TypeError: Cannot read property 'examples/lib/areas/demo.js' of undefined
    at getComponent (/Users/greada/Workspace/Github/react-spring/node_modules/@patternplate/api/lib/demo.js:405:10)
    at /Users/greada/Workspace/Github/react-spring/node_modules/@patternplate/api/lib/demo.js:353:29
    at /Users/greada/Workspace/Github/react-spring/node_modules/@patternplate/client/lib/app/render-page/index.js:99458:27
    at <anonymous>
```

## Chrome

```
GET http://localhost:1337/api/demo/areas.html 500 (Internal Server Error) areas?components-enabled=true:403
```

## versions

```
"@patternplate/cli": "^2.5.4",
"@patternplate/render-react": "^2.5.2",
```

## config

```js
module.exports = {
  docs: ['./API*.md'],
  entry: ['./examples/lib/**/demo.js'],
  render: '@patternplate/render-react/render',
  mount: '@patternplate/render-react/mount'
}
```

## jsx

```jsx
import React from 'react'

export default  () => <div>Hello World</div>
```

## js

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var _default = function _default() {
  return _react.default.createElement("div", null, "Hello World");
};

exports.default = _default;
```

**Comment by marionebl** [comment]
Please provide a link to the relevant repo / commit hash so I can reproduce.

**Comment by marionebl** [comment]
Without a repro this is not actionable. Please feel free to reopen when you can provide one.
