### ISSUE TITLE
@pattern/api: render().then is not a function

### ISSUE THREAD

**Issue by Dangoo** [patternplate/patternplate#236]
After update to @patternplate/api@2.5.19 with MR #234 there seems to be a problem with the babeled output:
```
TypeError: render(...).then is not a function
[0]     at /<ProjectPath>/node_modules/@patternplate/api/lib/demo.js:350:49
[0]     at /<ProjectPath>/node_modules/@patternplate/client/lib/app/render-page/index.js:99457:27
[0]     at <anonymous>
```

**Comment by Dangoo** [comment]
Duplicate with #235
